version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    build: .
    command: bundle exec puma -C config/puma.rb -e development -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db