default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', '') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'root') %>
  pool: 5

development:
  <<: *default
  database: Rubyist-connect_development

test:
  <<: *default
  database: Rubyist-connect_test
